- import_playbook: nginx-setup.yml

- import_playbook: install-postgresql.yml
- import_playbook: zabbix-server.yml
- import_playbook: zabbix-web-setup.yml
- import_playbook: zabbix-agents.yml

- import_playbook: elasticsearch.yml
- import_playbook: kibana.yml
- import_playbook: filebeat.yml